version: "3"
services:
  lavalink:
    hostname: lavalink
    image: fredboat/lavalink:master-v3
    environment:
      LAVALINK_SERVER_PASSWORD: fdsaolkjpdeswfnoikdejohgtlnty54oiu54y908pi54tytjhyt5
      SERVER_PORT: 2333
      SERVER_HOST: 0.0.0.0
    ports:
       - 2333:2333
