name: Build Project and push to docker

on:
  push:
    branches:
      - "master"

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}   # checkout the correct branch name
        fetch-depth: 0                # fetch the whole repo history
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ERIK.Bot.Python/.
        file: ERIK.Bot.Python/Dockerfile 
        pull: true
        push: true
        cache-from: type=registry,ref=enes1/erik:latest
        cache-to: type=inline
        tags: enes1/erik:latest
